CREATE TABLE [dbo].[tenk2012] (
    [address1]       NVARCHAR (50)    NOT NULL,
    [address2]       NVARCHAR (50)    NULL,
    [address3]       NVARCHAR (50)    NULL,
    [aff]            NVARCHAR (50)    NULL,
    [age]            INT              NULL,
    [club]           NVARCHAR (50)    NULL,
    [county]         NVARCHAR (50)    NULL,
    [dec]            NVARCHAR (50)    NULL,
    [dob]            DATETIME         NULL,
    [email]          NVARCHAR (50)    NULL,
    [fee]            INT              NULL,
    [form]           NVARCHAR (50)    NULL,
    [grade]          NVARCHAR (50)    NULL,
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [lname]          NVARCHAR (50)    NULL,
    [mobile]         NVARCHAR (50)    NULL,
    [name]           NVARCHAR (50)    NULL,
    [newsletter]     NVARCHAR (50)    NULL,
    [number]         INT              NULL,
    [number1]        INT              NULL,
    [paid]           NVARCHAR (50)    NULL,
    [phone]          NVARCHAR (50)    NULL,
    [postcode]       NVARCHAR (50)    NULL,
    [prn]            INT              NULL,
    [race]           NVARCHAR (50)    NULL,
    [receipt]        NVARCHAR (50)    NULL,
    [rn]             INT              NULL,
    [sent]           NVARCHAR (50)    NULL,
    [sex]            NVARCHAR (50)    NULL,
    [title]          NVARCHAR (50)    NULL,
    [udate]          DATETIME         NULL,
    [gp]             CHAR (10)        NULL,
    [date]           DATETIME         NULL,
    [message]        CHAR (10)        NULL,
    [transaction_id] VARCHAR (30)     NULL,
    [rn2]            UNIQUEIDENTIFIER NULL,
    [ukaNumber]      VARCHAR (50)     NULL,
    [IpnDetails]     VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_tenk] PRIMARY KEY CLUSTERED ([Id] ASC)
);

