//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int EntryId { get; set; }
        public bool Race { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string CityTown { get; set; }
        public string County { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
