//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class info2
    {
        public int ID { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string extra { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
