//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HacEntities : DbContext
    {
        public HacEntities()
            : base("name=HacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Applications { get; set; }
        public DbSet<Entry> Entries { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<funrun> funruns { get; set; }
        public DbSet<info> infoes { get; set; }
        public DbSet<info2> info2 { get; set; }
        public DbSet<link> links { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<membership> memberships { get; set; }
        public DbSet<Membership1> Memberships1 { get; set; }
        public DbSet<PIC_CATEGORIES> PIC_CATEGORIES { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<Profile1> Profiles1 { get; set; }
        public DbSet<result> results { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tenk2012> tenk2012 { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersInRole> UsersInRoles { get; set; }
    }
}
