//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIC_CATEGORIES
    {
        public int CAT_ID { get; set; }
        public string CAT_NAME { get; set; }
        public string CAT_IMAGE { get; set; }
        public string CAT_DESC { get; set; }
    }
}
