//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenk2012
    {
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string aff { get; set; }
        public Nullable<int> age { get; set; }
        public string club { get; set; }
        public string county { get; set; }
        public string dec { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public Nullable<int> fee { get; set; }
        public string form { get; set; }
        public string grade { get; set; }
        public int Id { get; set; }
        public string lname { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string newsletter { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> number1 { get; set; }
        public string paid { get; set; }
        public string phone { get; set; }
        public string postcode { get; set; }
        public Nullable<int> prn { get; set; }
        public string race { get; set; }
        public string receipt { get; set; }
        public Nullable<int> rn { get; set; }
        public string sent { get; set; }
        public string sex { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string gp { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message { get; set; }
        public string transaction_id { get; set; }
        public Nullable<System.Guid> rn2 { get; set; }
        public string ukaNumber { get; set; }
        public string IpnDetails { get; set; }
    }
}
